object TEST_ProtokollShowForm: TTEST_ProtokollShowForm
  Left = 301
  Top = 104
  Width = 769
  Height = 819
  AutoSize = True
  Caption = 'Protokoll'
  Color = clBtnFace
  DefaultMonitor = dmMainForm
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 18
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 761
    Height = 737
    BevelInner = bvLowered
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object ProtokollListBox: TListBox
      Left = 8
      Top = 8
      Width = 745
      Height = 673
      Font.Charset = ARABIC_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Courier'
      Font.Pitch = fpFixed
      Font.Style = []
      ItemHeight = 17
      ParentFont = False
      TabOrder = 0
    end
    object PrintButton: TButton
      Left = 544
      Top = 696
      Width = 89
      Height = 33
      Caption = 'Drucken'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = PrintButtonClick
    end
    object SaveButton: TButton
      Left = 664
      Top = 696
      Width = 89
      Height = 33
      Caption = 'Speichern'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      OnClick = SaveButtonClick
    end
  end
  object ButtonClose: TButton
    Left = 328
    Top = 752
    Width = 129
    Height = 33
    Caption = 'Schliessen'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
    OnClick = ButtonCloseClick
  end
  object PrintDialog1: TPrintDialog
    Left = 96
    Top = 744
  end
  object SaveDialog1: TSaveDialog
    Left = 128
    Top = 744
  end
end
